# Documentation for .goreleaser.yml can be found at <https://goreleaser.com>.
---
before:
  hooks:
    - go mod tidy
    - make codegen
    #- make -C gui
env:
  - CGO_ENABLED=0
builds:
  # This is the build for use in the install script.
  - id: autoinstalled
    main: .
    goos:
      - linux
      - darwin
    tags:
      - bundle

  # This is the build for use by package managers.
  - id: managed
    main: .
    goos:
      - linux
      - darwin
    tags:
      - bundle
      - managed

archives:
  - id: autoinstalled
    name_template:  '{{ .ProjectName }}_autoinstalled_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    builds: ["autoinstalled"]
    wrap_in_directory: true
    files:
      - LICENSE
      - NOTICES.md
      - VERSION
      - README.md
      - doc/*
  - id: managed
    name_template:  '{{ .ProjectName }}_managed_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    builds: ["managed"]
    wrap_in_directory: true
    files:
      - LICENSE
      - NOTICES.md
      - VERSION
      - README.md
      - doc/*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: exo
    ids: ["managed"]
    tap:
      owner: deref
      name: homebrew-tap
    commit_author:
      name: derefbot
      email: bot@deref.io
    homepage: "https://exo.deref.io"
    folder: Formula
    test: |
      system "#{bin}/exo version"

nfpms:
  - builds: ["managed"]
    formats:
    - apk
    - deb
    - rpm

release:
  github:
    owner: deref
    name: exo
  disable: true
