blank_issues_enabled: false
contact_links:
  - name: exo Slack Community
    url: https://join.slack.com/t/deref-community/shared_invite/zt-tu8arun7-qqpVcTe3IDHjpSG_TrSaBQ
    about: Slack community for discussion about exo use and development.
